//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.BondTransactions = new HashSet<BondTransaction>();
            this.CashTransactions = new HashSet<CashTransaction>();
            this.ConsultancyExpenses = new HashSet<ConsultancyExpens>();
            this.CouponPayments = new HashSet<CouponPayment>();
            this.Dividends = new HashSet<Dividend>();
            this.EquityTransactions = new HashSet<EquityTransaction>();
            this.InsuranceTransactions = new HashSet<InsuranceTransaction>();
            this.Interests = new HashSet<Interest>();
            this.MarginLendingTransactions = new HashSet<MarginLendingTransaction>();
            this.MortgageHomeLoanTransactions = new HashSet<MortgageHomeLoanTransaction>();
            this.PropertyTransactions = new HashSet<PropertyTransaction>();
            this.Rentals = new HashSet<Rental>();
            this.RepaymentRecords = new HashSet<RepaymentRecord>();
        }
    
        public string AccountId { get; set; }
        public string AccountNumber { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int AccountType { get; set; }
        public string AccountInfo { get; set; }
        public string Client_ClientId { get; set; }
        public string ClientGroup_ClientGroupId { get; set; }
    
        public virtual ClientGroup ClientGroup { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BondTransaction> BondTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashTransaction> CashTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultancyExpens> ConsultancyExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponPayment> CouponPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dividend> Dividends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquityTransaction> EquityTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceTransaction> InsuranceTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interest> Interests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarginLendingTransaction> MarginLendingTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MortgageHomeLoanTransaction> MortgageHomeLoanTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyTransaction> PropertyTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental> Rentals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepaymentRecord> RepaymentRecords { get; set; }
    }
}
