//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adviser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adviser()
        {
            this.ClientGroups = new HashSet<ClientGroup>();
            this.ConsultancyExpenses = new HashSet<ConsultancyExpens>();
            this.TransactionExpenses = new HashSet<TransactionExpens>();
        }
    
        public string AdviserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string AdviserNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int VerifiedId { get; set; }
        public string ABNACN { get; set; }
        public string AddressLn1 { get; set; }
        public string AddressLn2 { get; set; }
        public string AddressLn3 { get; set; }
        public string State { get; set; }
        public string Suburb { get; set; }
        public string Country { get; set; }
        public string PostCode { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string CompanyName { get; set; }
        public string CurrentTitle { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> ExperienceStartDate { get; set; }
        public string MiddleName { get; set; }
        public string Title { get; set; }
        public Nullable<double> Lng { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public byte[] Image { get; set; }
        public string ImageMimeType { get; set; }
        public Nullable<System.DateTime> IndustryExperienceStartDate { get; set; }
        public string BusinessPhone { get; set; }
        public string BusinessMobile { get; set; }
        public string BusinessFax { get; set; }
        public string RoleAndServicesSummary { get; set; }
        public string DealerGroupName { get; set; }
        public string Asfl { get; set; }
        public string DAddressLine1 { get; set; }
        public string DAddressLine2 { get; set; }
        public string DAddressLine3 { get; set; }
        public string DSuburb { get; set; }
        public string DState { get; set; }
        public string DPostcode { get; set; }
        public string DCountry { get; set; }
        public bool DealerGroupHasDerivativesLicense { get; set; }
        public bool IsAuthorizedRepresentative { get; set; }
        public string AuthorizedRepresentativeNumber { get; set; }
        public string TotalAssetUnderManagement { get; set; }
        public string TotalInvestmentUndermanagement { get; set; }
        public string TotalDirectAustralianEquitiesUnderManagement { get; set; }
        public string TotalDirectInterantionalEquitiesUnderManagement { get; set; }
        public string TotalDirectFixedInterestUnderManagement { get; set; }
        public string TotalDirectLendingBookInterestUnderManagement { get; set; }
        public string ApproximateNumberOfClients { get; set; }
        public string Institution { get; set; }
        public int EducationLevelId { get; set; }
        public string CourseTitle { get; set; }
        public bool CourseStatus { get; set; }
        public string ProfessiontypeId { get; set; }
        public int NewsLetterServiceId { get; set; }
        public string NewsLetterServiceName { get; set; }
        public bool NewsLetterSelected { get; set; }
        public string GroupName { get; set; }
        public int ServiceId { get; set; }
        public string ServiceName { get; set; }
        public bool Providing { get; set; }
        public int CAFId { get; set; }
        public bool CAFSelected { get; set; }
        public string CAFDescription { get; set; }
        public bool RemunerationMethodSpecified { get; set; }
        public string RemunerationMethod { get; set; }
        public int NumberOfClientsId { get; set; }
        public int InvestibleAssetLevel { get; set; }
        public int TotalAssetLevelId { get; set; }
        public int AnnualIncomeLevelId { get; set; }
        public string TotalAssetLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientGroup> ClientGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultancyExpens> ConsultancyExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionExpens> TransactionExpenses { get; set; }
    }
}
