//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashAccount()
        {
            this.CashTransactions = new HashSet<CashTransaction>();
            this.Interests = new HashSet<Interest>();
        }
    
        public string Id { get; set; }
        public string Bsb { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public int CashAccountType { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public int Frequency { get; set; }
        public int CurrencyType { get; set; }
        public Nullable<int> TermsInMonths { get; set; }
        public Nullable<double> InterestRate { get; set; }
        public Nullable<double> AnnualInterest { get; set; }
        public double FaceValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashTransaction> CashTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interest> Interests { get; set; }
    }
}
