//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class edisDbEntities : DbContext
    {
        public edisDbEntities()
            : base("name=edisDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Adviser> Advisers { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AssetPrice> AssetPrices { get; set; }
        public virtual DbSet<AustralianState> AustralianStates { get; set; }
        public virtual DbSet<Bond> Bonds { get; set; }
        public virtual DbSet<BondTransaction> BondTransactions { get; set; }
        public virtual DbSet<BondType> BondTypes { get; set; }
        public virtual DbSet<CashAccount> CashAccounts { get; set; }
        public virtual DbSet<CashTransaction> CashTransactions { get; set; }
        public virtual DbSet<ClientGroup> ClientGroups { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ConsultancyExpens> ConsultancyExpenses { get; set; }
        public virtual DbSet<CouponPayment> CouponPayments { get; set; }
        public virtual DbSet<Dividend> Dividends { get; set; }
        public virtual DbSet<Equity> Equities { get; set; }
        public virtual DbSet<EquityTransaction> EquityTransactions { get; set; }
        public virtual DbSet<IndexedEquity> IndexedEquities { get; set; }
        public virtual DbSet<InsuranceTransaction> InsuranceTransactions { get; set; }
        public virtual DbSet<Interest> Interests { get; set; }
        public virtual DbSet<LiabilityRate> LiabilityRates { get; set; }
        public virtual DbSet<LoanValueRatio> LoanValueRatios { get; set; }
        public virtual DbSet<MarginLendingTransaction> MarginLendingTransactions { get; set; }
        public virtual DbSet<MortgageHomeLoanTransaction> MortgageHomeLoanTransactions { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<PropertyTransaction> PropertyTransactions { get; set; }
        public virtual DbSet<PropertyType> PropertyTypes { get; set; }
        public virtual DbSet<Rental> Rentals { get; set; }
        public virtual DbSet<RepaymentRecord> RepaymentRecords { get; set; }
        public virtual DbSet<ResearchValue> ResearchValues { get; set; }
        public virtual DbSet<Sector> Sectors { get; set; }
        public virtual DbSet<TransactionExpens> TransactionExpenses { get; set; }
    }
}
