//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndexedEquity
    {
        public string Id { get; set; }
        public string Ticker { get; set; }
        public string Name { get; set; }
        public double Weighting { get; set; }
        public int AsxIndexTypes { get; set; }
        public int EquityType { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
