//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceTransaction
    {
        public string Id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime PurchasedOn { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string EntitiesInsured { get; set; }
        public bool IsAcquire { get; set; }
        public string Issuer { get; set; }
        public int InsuranceType { get; set; }
        public int PolicyType { get; set; }
        public string PolicyNumber { get; set; }
        public string NameOfPolicy { get; set; }
        public string PolicyAddress { get; set; }
        public double AmountInsured { get; set; }
        public double Premium { get; set; }
        public string AccountId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
