//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiabilityRate
    {
        public string Id { get; set; }
        public double Rate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public string MortgageId { get; set; }
        public string MarginLendingId { get; set; }
    
        public virtual MarginLendingTransaction MarginLendingTransaction { get; set; }
        public virtual MortgageHomeLoanTransaction MortgageHomeLoanTransaction { get; set; }
    }
}
