//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanValueRatio
    {
        public string Id { get; set; }
        public double Ratio { get; set; }
        public string AssetId { get; set; }
        public int AssetTypes { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ActiveDate { get; set; }
        public string MarginLendingTransaction_Id { get; set; }
    
        public virtual MarginLendingTransaction MarginLendingTransaction { get; set; }
    }
}
