//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarginLendingTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarginLendingTransaction()
        {
            this.LiabilityRates = new HashSet<LiabilityRate>();
            this.LoanValueRatios = new HashSet<LoanValueRatio>();
        }
    
        public string Id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime GrantedOn { get; set; }
        public double LoanAmount { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public bool IsAcquire { get; set; }
        public string AccountId { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiabilityRate> LiabilityRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanValueRatio> LoanValueRatios { get; set; }
    }
}
