//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Note()
        {
            this.Attachments = new HashSet<Attachment>();
        }
    
        public string NoteId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Subject { get; set; }
        public int NoteType { get; set; }
        public int SenderRole { get; set; }
        public System.DateTime DateModified { get; set; }
        public string AdviserId { get; set; }
        public string AssetClass { get; set; }
        public string ProductClass { get; set; }
        public string Product { get; set; }
        public string Purpose { get; set; }
        public float TimeSpend { get; set; }
        public string NoteSerial { get; set; }
        public string Body { get; set; }
        public string FollowupActions { get; set; }
        public System.DateTime DateDue { get; set; }
        public System.DateTime FollowupDate { get; set; }
        public System.DateTime DateCompleted { get; set; }
        public System.DateTime ReminderDate { get; set; }
        public string Status { get; set; }
        public bool Reminder { get; set; }
        public bool IsAccepted { get; set; }
        public bool IsDeclined { get; set; }
        public string AssetTypeId { get; set; }
        public string AccountId { get; set; }
        public string ClientId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual Client Client { get; set; }
    }
}
