//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteLink
    {
        public string Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string NoteId1 { get; set; }
        public string NoteId2 { get; set; }
    }
}
