//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepaymentRecord
    {
        public string Id { get; set; }
        public string CorrespondingLiabilityGroupingKey { get; set; }
        public int LiabilityType { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime PaymentOn { get; set; }
        public double PrincipleAmount { get; set; }
        public double InterestAmount { get; set; }
        public string AccountId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
