//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearchValue
    {
        public string Id { get; set; }
        public string Key { get; set; }
        public double Value { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Issuer { get; set; }
        public string Bond_BondId { get; set; }
        public string Property_PropertyId { get; set; }
        public string Equity_AssetId { get; set; }
        public string StringValue { get; set; }
    
        public virtual Bond Bond { get; set; }
        public virtual Equity Equity { get; set; }
        public virtual Property Property { get; set; }
    }
}
