//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourcesReference
    {
        public string Id { get; set; }
        public string TokenValue { get; set; }
        public string FileExtension { get; set; }
        public string ResourceUrl { get; set; }
        public string UserId { get; set; }
    }
}
