//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionExpens
    {
        public string Id { get; set; }
        public System.DateTime IncurredOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public double Amount { get; set; }
        public int ExpenseType { get; set; }
        public int TransactionType { get; set; }
        public string CorrespondingTransactionId { get; set; }
        public string AdviserId { get; set; }
    
        public virtual Adviser Adviser { get; set; }
    }
}
